apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
spec:
  selector:
    matchLabels:
      app: app-tier
  template:
    metadata:
      labels:
        app: app-tier
    spec:
      containers:
        - name: app-tier
          image: iodinehanifan/laravel-app:1.7
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              value: base64:kp/M0Ml0r3MdfQF6kwXamCP/FmV+Esq3dsXYfzgUkcA=
